# Generated by Django 3.0.2 on 2020-01-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20200128_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='InfoUpdate',
        ),
    ]
